### ISSUE TITLE
[新需求]希望可以增量构建字体库

### ISSUE THREAD

**Issue by fuxin052** [wyzdwdz/assfonts#1]
您好, 用了几天这个工具, 感谢非常好用

在使用时我都会把缺少的字体放进字体库重新构建, 但是每次都是全量的, 速度很慢(因为文件夹字体很多)
所以能不能只检查json文件里没有的字体并加入, 这样应该能快很多

**Comment by wyzdwdz** [comment]
v0.3.6 添加了增量更新的功能，使用前需要重新建立字体库
