### ISSUE TITLE
[新功能]多个字幕共同输出一个字集化结果的功能

### ISSUE THREAD

**Issue by CarefulDeveloper** [wyzdwdz/assfonts#10]
目前在新版(v0.6.1)中，输入多个字幕是会输出对应多个字幕的字体子集化结果的，但是存在这样一种情况：

一个视频有多个语言的字幕(比如：input.chs.ass, input.cht.ass)，此时我期望输入这两个字幕，然后共享一个子集化的结果。

希望作者有时间能够实现这个功能，谢谢。

**Comment by wyzdwdz** [comment]
这个功能可以考虑实现，但是由于原程序每个字幕是由单独线程独立处理的，所以需要做一些额外的工作改一下底层的结构，
目前暂定在下一个小版本推出这个功能的测试版

**Comment by wyzdwdz** [comment]
new feature added
