### ISSUE TITLE
一些UX、用户体验优化

### ISSUE THREAD

**Issue by honeyjuice** [wyzdwdz/assfonts#11]
以下为WIndows GUI客户端的优化建议

1.建立数据库后，字体目录不要清空
使用场景：
子集化失败，查看日志发现缺字体后，打开浏览器，下载拖到超级字体包里进行补充-->发现目录为空->重新输入路径->再次重建数据库
希望优化成
设置好固定字体目录
发现缺字体->下载拖入字体路径->重建数据库

2.可以固定输出目录
使用场景：
D:\临时文件 是我的输出专用目录，而字体往往会在其他各个临时目录 ，如windows的下载目录
拖入字体->修改输出目录->子集化  
希望优化成
设置好固定输出目录
之后拖入字体->子集化  

3.结束后删除过程文件，或将过程文件归集到一个和输出目录无关的文件夹中
使用场景：
子集化->打开输出目录->从一堆文件中找出.rename.assfonts.ass ->拖入filebot进行文件名批量整理
![图片](https://github.com/wyzdwdz/assfonts/assets/32090001/734c0341-d6a1-42c6-8797-e7fb86193c9a)
![图片](https://github.com/wyzdwdz/assfonts/assets/32090001/d3ce8f78-ae8a-427d-aa7d-924076c33fdb)

希望仅仅保留子集化后的字幕，优化整个工作流变成
子集化->直接将输出目录拖入filebot进行文件名批量整理

**Comment by wyzdwdz** [comment]
针对 1 和 2，
需要重新说明一下 font directory 这个文件夹的作用。在 build database 的时候，软件会扫描 font directory 中的字体并更新数据库；在 run 的时候，font directory 会作为一个临时的字体路径，软件会首先扫描 font directory 中的字体是否有符合字幕要求的，如果没有再去从数据库中找字体。所以 build database 后会自动清空 font directory，以免 run 的时候再次扫描一遍这个文件夹。

针对3，
这是一个很好的建议，下一个版本我会改进。

另外，由于软件最早期仅仅是作为命令行程序进行开发的，并不是一个原生的 GUI 软件，所以后来加入的 GUI，也仅仅是作为命令行程序的拓展，保持了命令行的运行逻辑，因此体验上会一些反直觉的地方，导致使用起来效率不高。像楼主的大批量处理需求，尤其是许多客制化的部分，使用 GUI 确实不会很方便，这种情况建议写 bat 或 powershell 脚本并配合 assfonts.exe 这个命令行程序解决。
