### ISSUE TITLE
可以为armv7编译一份吗？

### ISSUE THREAD

**Issue by heddxh** [wyzdwdz/assfonts#12]
不知为何我在 Arch Linux ArmV7 上编译会报:
```
ERROR: There are invalid packages:
cmake/3.26.3: Invalid: CMake binaries are only provided for x86_64 and armv8 architectures
```

**Comment by wyzdwdz** [comment]
新版的 CMake 只有 64 位版本的，所以编译 armv7 必须要交叉编译。
目前本程序暂时不提供 32 位的二进制文件。

**Comment by wyzdwdz** [comment]
conan qt5 对 32 位系统的支持存在 bug，无法通过编译，目前只能等待上游修复。我在考虑转移 conan 到 vcpkg，目前还在测试中，希望可以解决这个问题。
