### ISSUE TITLE
win10 iot企业版（又叫tiny10精简版）无法打开程序

### ISSUE THREAD

**Issue by samir2015dzh** [wyzdwdz/assfonts#17]
大佬，这个是我的系统信息

![image](https://github.com/user-attachments/assets/e8a9c057-4b7c-4c00-9bb9-d5a30d2df113)

打开会提示这个
![image](https://github.com/user-attachments/assets/180b8749-477b-4f36-baaf-6e02d5a6c005)

**Comment by wyzdwdz** [comment]
你需要下载 x86_64 版本的程序，aarch64 无法在 x64 的电脑上运行
