### ISSUE TITLE
\r未知样式的问题

### ISSUE THREAD

**Issue by fuxin052** [wyzdwdz/assfonts#2]
对于这种不规范的写法, 如{\rhaha}, 并且未指定haha这个样式
经过测试发现mpv上的效果等同于{\r}, 即使用当前行所指定的样式

而本程序会直接跳过后面的文字的子集化, 从而导致可能会缺字

**Comment by wyzdwdz** [comment]
问题已修复

**Comment by fuxin052** [comment]
请问后续还会编译命令行版本吗
