### ISSUE TITLE
方正悠宋 GBK 507r无法子集化

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [wyzdwdz/assfonts#6]
<img width="541" alt="image" src="https://github.com/wyzdwdz/assfonts/assets/78670748/aa94cc84-3c97-40bf-a67d-f54b311d05f5">

更换了好几个ttf，好几个组的字幕有这个都无法子集化

**Comment by wyzdwdz** [comment]
这个字体的 GSUB 中存在未定义或者无法识别的子表，所以无法做子集化。经测试，方正悠宋 GBK 系列的多个字体都存在这个问题，可能是字体在制作时引入的问题，不过我并不很了解字体制作，所以无法给出针对该字体的修改建议。如果可以的话，你可以尝试用 fontforge 重新导出一遍这个字体，应该就能自动消除字体不规范的地方。

**Comment by fuxin052** [comment]
超级字体库的不行
需要去方正官网下载, 整个方正悠宋系列都这样
