### ISSUE TITLE
[BUG] subfonts rename 当某字体名称为另一字体名称前缀时，字体名称替换错误

### ISSUE THREAD

**Issue by a2123228** [wyzdwdz/assfonts#9]
正确情况：方正兰亭圆_GBK_准 -> ZNZOOHWY
bad.ass：方正兰亭圆_GBK_准 -> JHBAHEGA_准
[file.zip](https://github.com/wyzdwdz/assfonts/files/13178494/file.zip)

**Comment by wyzdwdz** [comment]
bug fixed
